from .config import (
    EMB_MODEL_PATH,
    QDRANT_PATH,
    QDRANT_URL,
    COLLECTION_NAME,
    VECTOR_DIM,
    DEFAULT_CHUNK_OVERLAP,
    DEFAULT_CHUNK_SIZE,
    API_KEY,
    ALLOWED_FILE_TYPES
)